## Craping the Data from "Find Easy" website

In [8]:
import os
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the website
url = "https://www.findeasy.in/tobacco-use-among-adults-in-india/"

# Send a request to the website and get the HTML content
response = requests.get(url)
html_content = response.text

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html_content, "html.parser")

# Find the table body (tbody) element
table_body = soup.find("tbody")

# Create a list to store the data rows
data_rows = []

# Find all the rows (tr) within the table body
for idx, row in enumerate(table_body.find_all("tr")):
    # Skip the first row (contains column headers)
    if idx == 0:
        continue
    # Find all the cells (td) within each row
    cells = row.find_all("td")
    # Extract the data and store it in a list
    row_data = [cell.text.strip() for cell in cells]
    # Append the row data to the list of data rows
    data_rows.append(row_data)

# Create a DataFrame from the list of data rows
df = pd.DataFrame(data_rows, columns=["Sl. No", "States & Union Territories", "Women (15 years & above)", "Men (15 years & above)"])

In [9]:
df

,Sl. No,States & Union Territories,Women (15 years & above),Men (15 years & above)
0,1,Andaman &Â Nicobar,31.3 %,58.7 %
1,2,AP,3.8%,22.6%
2,3,Arunachal,18.8%,50.3%
3,4,Assam,22.1%,51.8%
4,5,Bihar,5.0%,48.8%
5,6,Chandigarh,0.6%,12.1%
6,7,Chattishgarh,17.3%,43.1%
7,8,D&N,2.9%,38.6%
8,9,Delhi,2.2%,26.3%
9,10,Goa,2.6%,18.2%
10,11,Gujarat,8.7%,41.1%
11,12,Haryana,2.5%,29.1%
12,13,Himachal Pradesh,1.7%,32.3%
13,14,J&K,3.6%,38.3%
14,15,Jharkhand,8.4%,47.4%
15,16,Karnataka,8.5%,27.1%
16,17,Kerala,2.2%,16.9%
17,18,Ladakh,3.2%,35.7%
18,19,Lakshadweep,17.5%,28.5%
19,20,Maharashtra,10.9%,33.8%
20,21,Manipur,43.1%,58.1%
21,22,Meghalaya,28.2%,57.7%
22,23,Mizoram,61.6%,72.9%
23,24,Madhya Pradesh,10.2%,46.5%
24,25,Nagaland,13.7%,48.4%
25,26,Odisha,26.0%,51.6%
26,27,Puducherry,2.6%,14.8%
27,28,Punjab,0.4%,12.9%
28,29,Rajasthan,6.9%,42.0%
29,30,Sikkim,11.7%,41.3%
30,31,Tamil Nadu,4.9%,20.1%
31,32,Telangana,5.6%,22.3%
32,33,Tripura,50.4%,56.9%
33,34,Uttar Pradesh,8.4%,44.1%
34,35,Uttarakhand,4.6%,33.7%
35,36,West Bengal,10.8%,48.1%
36,,India,8.9%,38.0%

In [10]:
# Save the DataFrame to a CSV file
file_path = "tobacco_data.csv"
df.to_csv(file_path, index=False)

print("Tobacco data has been scraped and saved to:", file_path)

Tobacco data has been scraped and saved to: tobacco_data.csv